### ISSUE TITLE
Affinity to the end of a `link` mark does not retain after typing

### ISSUE THREAD

**Issue by dragonman225** [ocavue/prosemirror-virtual-cursor#17]
When typing at the end of a `link` mark with affinity pointing to it, only the first character being typed becomes part of the link, after that, the affinity changes to point to the right, and more characters being typed do not becomes part of the link.

In contrast, when typing the end of a `bold`/`strong` mark with affinity pointing to it, the affinity doesn't change, and all characters being typed becomes bold.

https://github.com/ocavue/prosemirror-virtual-cursor/assets/25148955/b0674fa9-ed91-4931-819f-4081f90d0435

Browser I was using: Google Chrome 115.0.5790.114

**Comment by ocavue** [comment]
To explain, the direct reason behind this difference is that link has [`inclusive: false`](https://github.com/ProseMirror/prosemirror-schema-basic/blob/cbd834fed35ce70c56a42d387fe1c3109187935e/src/schema-basic.ts#L118) in its schema spec. This means the link mark will be inactive by default when the text cursor is at the end of a link. 

I will improve the behavior for such kinds of marks in prosemirror-virtual-cursor.

**Comment by dragonman225** [comment]
I see, that makes sense.

I wonder if it's OK to ignore the `inclusive` property in situations where affinity is in effect, that is, when the cursor can have a tail, since in such situations prosemirror-virtual-cursor is solving the same problem that `inclusive` is solving, and in a better way!

And when there's no sides to choose, for example, at the end of the textblock, respect the `inclusive` property:

https://github.com/ocavue/prosemirror-virtual-cursor/assets/25148955/1faf2789-7dec-4364-8998-6bbc5ed058d5

**Comment by kkshinkai** [comment]
You can support marks with `inclusive: false` by dynamically setting all stored marks' schema spec to `inclusive: true` on key down and resetting them on key up. This method even handles IME correctly. However, it involves dynamically modifying the schema, which is a bit of a hack. Just FYI.

**Comment by ocavue** [comment]
I agree that's bit of a hack. Let me link your comment in README as a hit.

**Comment by ocavue** [comment]
Is there any difference in behavior between (a) setting all mark specs to `inclusive: true` before creating schema, and (b) dynamically changing schema specs to `inclusive: true` on key down and resetting them later?

**Comment by kkshinkai** [comment]
Doesn't seem different to me, but I've only done a bit of testing. Not sure what Marijn thinks about dynamic schemas, though.

**Comment by ocavue** [comment]
If there is no difference in behavior, then I think _explicitly_ setting `inclusive` (by users) would be better than _inexplicitly_ (by this plugin).
