### ISSUE TITLE
Issue with Text Selection Background Color on iOS Browsers

### ISSUE THREAD

**Issue by totorofly** [ocavue/prosemirror-virtual-cursor#35]
Description:
This plugin works quite well on desktop. However, when selecting text in iOS browsers, the background color of the selected text changes to gray. Is there an easy fix for this issue?

![图片](https://github.com/ocavue/prosemirror-virtual-cursor/assets/41875799/443f4376-1840-4f02-9531-3fae60552de5)

**Comment by ocavue** [comment]
You can remove [`caret-color: transparent;`](https://github.com/ocavue/prosemirror-virtual-cursor/blob/d140662204b8a695493ed968fb07d1e7a4976db9/style/virtual-cursor.css#L3) on iOS. 



![prosemirror-virtual-cursor](https://github.com/ocavue/prosemirror-virtual-cursor/assets/24715727/44cd9f00-68fc-46aa-9e98-ab1562a59580)
