### ISSUE TITLE
Mouse dragging doesn't create a selection

### ISSUE THREAD

**Issue by ocavue** [ocavue/prosemirror-virtual-cursor#4]
## Steps to reproduce 

1. Open https://prosemirror-virtual-cursor.vercel.app/
2. Put the cursor at the start of the heading
3. Move the mouse over the _left_ part of the letter m
4. Press and drag the mouse to the left side

## Expected behavior

The text at the left side of `m` will be selected

## Actual behavior 

The cursor is moving but nothing is selected

## Extra context

If the mouse if over the right part of the letter, then every thing is normal

I see this issue sometime in a vanilla ProseMirror editor (i.e. without `prosemirror-vitual-cursor`). But I haven't found a way to 100% reproduce it in a vanilla ProseMirror editor. 

## Environment

- macOS 12.6
- Chrome 107

## Video 

https://user-images.githubusercontent.com/24715727/202668046-8d788a4c-5779-48ac-8191-4106d619d679.mp4

**Comment by Benbinbin** [comment]
> I see this issue sometime in a vanilla ProseMirror editor

I can reproduce this weird caret behavior at [lint example](https://prosemirror.net/examples/lint/) in Chrome, maybe something wrong with Chrome

a [relative post](https://discuss.prosemirror.net/t/mouse-selection-unexpected-behaviour/5425/3) at ProseMirror discuss
